### ISSUE TITLE
Problem with definition

### ISSUE THREAD

**Issue by Areczekk9** [rdbo/ImGui-DirectX-9-Kiero-Hook#4]
![image](https://user-images.githubusercontent.com/75174234/103155421-13f38d00-47a0-11eb-9e3c-ab72b4ee153b.png)
I have a problem with one line (GWL_WNDPROC) is defined and it shows an error that it is not.

**Comment by rdbo** [comment]
Just use this version, it's way better: https://github.com/rdbo/DX9-BaseHook
It supports unloading the DLL and has its own memory library.

... or keep using this one and add this:
```
#ifndef GWL_WNDPROC
#define GWL_WNDPROC GWLP_WNDPROC
#endif
```
This happens because on x64, GWL_WNDPROC is actually called GWLP_WNDPROC. This is an old project I coded quickly just to test Kiero so I probably didn't pay attention on this detail.
